export const DEFAULT_CONSUMER_LAST_NAME = 'sin'
export const DEFAULT_CONSUMER_NAME      = 'asignar'
export const DEFAULT_CONSUMER_EMAIL     = 'sin@asignar'
export const CARD_STATUS_CREATED        = "1"
export const CARD_STATUS_ACTIVATED       = "2"
export const CARD_STATUS_DISABLED       = "3"
export const CARD_STATUS_USED           = "4"
export const ORDER_CREATE               = "1"
export const ORDER_ACTIVATED            = "2"
export const ORDER_DISABLE              = "3"
export const ORDER_PARTIAL              = "4"
export const DEPOSIT                    = "1"
export const WITHDRAWAL                 = "2"
export const DESCRIPTION_DEPOSIT        = "init deposit"
export const MANDRILL_SUBJEcT           = "Haz recibido una gifcard"